--- 
avatar: "https://avatars3.githubusercontent.com/u/898478"
baseurl: ""
description: "Ostinato, Pensato, Scordatura"
disqus: drovani
exclude: 
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
footer-links: 
  dribbble: ~
  email: dev@rovani.net
  facebook: ~
  flickr: ~
  github: drovani
  googleplus: ~
  instagram: ~
  linkedin: ~
  pinterest: ~
  rss: ~
  stackoverflow: users/28310/drovani
  twitter: davidrovani
  youtube: ~
gems: 
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - Jekyll-paginate
google_analytics: UA-82341148-1
kramdown: 
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: 
    css_class: highlight
name: "Rovani in C#"
permalink: "/:title/"
sass: 
  style: !ruby/symbol expanded
url: ~
version: v1.2.0
